---
name: StatusViewer
main: kim\present\statusviewer\Loader
version: 0.1.0
api: [ 4.0.0 ]
author: PresentKim
description: Utility to easily check the status of the server

commands:
  statusview:
    description: On/off of Status viewer
    permission: statusview.cmd

permissions:
  statusview.cmd:
    description: /statusview command
    default: op
...